%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name rqt_runtime_monitor
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-rqt-runtime-monitor
Version:        1.0.0
Release:        6%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://wiki.ros.org/rqt_runtime_monitor
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
rqt_runtime_monitor provides a GUI plugin viewing DiagnosticsArray messages.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
rqt_runtime_monitor provides a GUI plugin viewing DiagnosticsArray messages.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
rqt_runtime_monitor provides a GUI plugin viewing DiagnosticsArray messages.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 Aaron Blasdel <ablasdel@gmail.com> - 1.0.0-6
- Autogenerated by Bloom

* Tue Apr 28 2026 Aaron Blasdel <ablasdel@gmail.com> - 1.0.0-5
- Autogenerated by Bloom

* Tue Apr 21 2026 Aaron Blasdel <ablasdel@gmail.com> - 1.0.0-4
- Autogenerated by Bloom
